Bring back Lomiri-specific notification hints
AyatanaIndicators/ayatana-indicator-datetime pull request #115
Opened 2023-12-06 19:22 UTC by peat-psuwit

As discussed in [1], Lomiri has a custom logic in notification timeout and require the custom hint for timeout to work correctly. Restore the hints from commit 0a88a8d7 ("Remove osd-notify remnants and use native notification timeout"), while keeping the standard timeout in place. Lomiri will ignore standard timeout, while other DE's will ignore the extra hint.

[1] https://gitlab.com/ubports/development/core/content-hub/-/merge_requests/32#note_1552217874

2023-12-06 20:20 UTC, sunweaver requested changes
Some minor changes for making this behave unnotified if not in Lomiri / if not built with Lomiri support. Thanks.

2023-12-06 20:20 UTC, sunweaver commented on src/notifications.cpp
> +                                          g_variant_new_int32(ms.count()));
@peat-psuwit thanks for the patch. Could we have this codepath only light up when the datetime indicators runs in Lomiri? Two conditions we need to check:

```
#ifdef LOMIRI_FEATURES_ENABLED
...
#endif
```

and 

```
if (ayatana_common_utils_is_lomiri()) {
    ...
}
```

Can you add that? Alternatively, make sure I can push to your PR branch and I'll update the patch myself.

2023-12-06 20:20 UTC, sunweaver commented on src/notifications.cpp
> +    static constexpr char const * HINT_LOMIRI_TIMEOUT {"x-lomiri-snap-decisions-timeout"};
ifdef around this, too...

2023-12-06 20:20 UTC, sunweaver commented on tests/notification-fixture.h
> +  static constexpr char const * HINT_LOMIRI_TIMEOUT {"x-lomiri-snap-decisions-timeout"};
also ifdef LOMIRI_FEATURES_ENABLED...

2023-12-06 20:20 UTC, sunweaver commented on tests/test-sound.cpp
> +
also ifdef...

2023-12-07 18:44 UTC, peat-psuwit commented on tests/test-sound.cpp
> +
Hmm... interesting. It turns out that `test-sound` are already tested only if `ENABLE_LOMIRI_FEATURES` is `ON` in CMake. Should I enable it otherwise too? If yes, I will also test that the hint is set on Lomiri and not set otherwise.

2023-12-07 20:11 UTC, sunweaver commented on tests/test-sound.cpp
> +
yeah, leave it as is...

2023-12-07 20:19 UTC, peat-psuwit commented on tests/test-sound.cpp
> +
Oh... I have a deeper revelation here: turns out, `Engine::show()` is called only in one place, in `snap.cpp`... which means that if a-i-datetime is built with `-DENABLE_LOMIRI_FEATURES=OFF`, notifications might not fire at all.

I guess the right course of action is to enable snap.cpp to be built without that flag, and then enable those 3 tests that are guarded by it. I wonder if it's worth doing though...

2023-12-19 15:55 UTC, sunweaver commented on tests/test-sound.cpp
> +
@peat-psuwit Now that you have fully dived into this, could you finalize this PR as proposed above?

2023-12-21 12:34 UTC, peat-psuwit commented on tests/test-sound.cpp
> +
I've reduced the number of things under `ENABLE_LOMIRI_FEATURES` to just a few things. However, now it's a draft, since there's a few more things to handle.

- I have to replace `PowerdWakeupTimer` with `MainloopWakeupTimer` and `Haptic` (hfd-service) with a stub one. I suppose it's not as easy as `ayatana_common_utils_is_lomiri()`, since it's also possible to run Lomiri without either of those. The facts that `PowerdWakeupTimer` is initialized asynchronously and we have to handle DBus service come and go pose further challenges. Is there a way to as DBus for known service name without actually start it?

- Maybe it's a good idea to let distributions set their own default calendar and alarm sound without `ENABLE_LOMIRI_FEATURES`.

2023-12-26 11:28 UTC, sunweaver commented on tests/test-sound.cpp
> +  class SoundNotificationFIxture : public NotificationFixture,
typo s/I/i/

2023-12-26 11:28 UTC, sunweaver commented on tests/test-sound.cpp
> +TEST_P(SoundNotificationFIxture, InteractiveDuration)
same typo here (s/I/i/)

2023-12-26 11:29 UTC, sunweaver commented on tests/test-sound.cpp
> +
> * Maybe it's a good idea to let distributions set their own default calendar and alarm sound without `ENABLE_LOMIRI_FEATURES`.

Yes, that would be good.

2023-12-26 11:31 UTC, sunweaver commented on tests/test-sound.cpp
> +
> * I have to replace `PowerdWakeupTimer` with `MainloopWakeupTimer` and `Haptic` (hfd-service) with a stub one. I suppose it's not as easy as `ayatana_common_utils_is_lomiri()`, since it's also possible to run Lomiri without either of those. The facts that `PowerdWakeupTimer` is initialized asynchronously and we have to handle DBus service come and go pose further challenges. Is there a way to as DBus for known service name without actually start it?

I am not sure if I am following here... We are speaking about unit tests, right? So let's assume a setup (e.g. with hfd-service) and test that code path. Right? Do you have any ETA for the completion of this MR?

2023-12-26 20:24 UTC, peat-psuwit commented on tests/test-sound.cpp
> +
No, not the test. Sorry for confusion. I specifically mean the code [here](https://github.com/AyatanaIndicators/ayatana-indicator-datetime/blob/main/src/main.cpp#L119) for Powerd, and [here](https://github.com/AyatanaIndicators/ayatana-indicator-datetime/blob/main/src/snap.cpp#L125-L133) for hfd-service.

I don't actually worry about hfd-service (desktop probably doesn't have haptic). However, I fear that without (Re)powerd, an alarm might not fire at all. However, the `PowerdWakeupTimer` specifically mentions that:

```c++
/* powerd isn't on the desktop, but we don't need hardware wakeups there
   anyway... so no need to warn on SERVICE_UNKNOWN */
```

So, I'm trying to figure out how it works in this case.

That said, I realize that merging this as-is could be an improvement on its own anyway. So, I'll now undraft this PR, and with the caveats above, merge at your discretion.

2023-12-26 20:36 UTC, peat-psuwit commented on tests/test-sound.cpp
> +  class SoundNotificationFIxture : public NotificationFixture,
Fixed in this and in all instances below.

2024-01-31 18:08 UTC, merged