W-I-P: UBports patches
AyatanaIndicators/ayatana-indicator-datetime pull request #46
Opened 2021-06-29 22:50 UTC by tari01

2021-07-02 04:12 UTC, sunweaver commented on src/menu.cpp
> + * off-screen on the phone, the menu should show the menu should show the
the menu should show the menu should show the menu should show... (repetition of words, please amend)

2021-07-14 18:02 UTC, peat-psuwit commented
I know a few things here:

> src/com.ubuntu.touch.AccountsService.Sound

This schema comes from [gsettings-ubuntu-touch-schemas](https://github.com/ubports/gsettings-ubuntu-touch-schemas/blob/xenial/accountsservice/com.ubuntu.AccountsService.Sound.xml). We need further discussion to determine what should eventually own this schema. A quick search suggested that it might also be used by indicator-power, indicator-sound, and ubuntu-push.

> x-canonical-snap-decisions-timeout

> x-canonical-snap-decisions

These are handled in [lomiri-notifications](https://gitlab.com/ubports/core/lomiri-notifications) ultimately Lomiri itself. Unfortunately, it's not renamed at the time lomiri-notifications was renamed. Perhaps it should be renamed, but is this the time?

Many of `x-canonical-*`, if passed via notifications, is probably handled by those 2.

> com.canonical.powerd

As of [the current repowerd rename MR](https://gitlab.com/ubports/core/repowerd/-/merge_requests/28), it's renamed to `com.lomiri.Repowerd`. The MR is not yet merged, but it should be soon.

> com.canonical.Unity.Screen

As of the current repowerd MR, this interface is _not_ renamed. The reason being that there are external users of this interface including at least 1 external app (see the MR).

> com.canonical.usensord

IIRC, we're planing to migrate from that to Marius's hfd-service.

> /usr/share/sounds/ubuntu

You probably need a build-time configuration for that. Per se it doesn't need to be an Ubuntu sound - any sound of supported format should work.

> include/datetime/settings-shared.h: 56: #define SETTINGS_NOTIFY_SCHEMA_ID "com.lomiri.notifications.settings"

This, too, comes from [gsettings-ubuntu-touch-schemas](https://github.com/ubports/gsettings-ubuntu-touch-schemas/blob/xenial/accountsservice/com.ubuntu.AccountsService.Sound.xml). A quick search seems like it's used in ubuntu-push.

2021-07-28 19:00 UTC, dobey requested changes
Found a few things that I think need fixing, from a quick look over.

2021-07-28 19:33 UTC, tari01 commented on CMakeLists.txt
> +pkg_check_modules(URLDISPATCHER lomiri-url-dispatcher>=0)
This must be conditional for all non-Lomiri environments, but I'm adding it to `debian/control` + `.build.yml`...

2021-07-28 19:47 UTC, tari01 commented on CMakeLists.txt
> +if (ENABLE_TESTS)
This block (along with some other CMake bits) is a kind of internal Ayatana standard - it is the same across all Ayatana components. It allows us to use our own flags instead of passing `CMAKE_BUILD_TYPE`. The build type is set according to the flags we pass in.

2021-07-28 19:50 UTC, tari01 commented on include/datetime/actions-live.h
> +    void lomiri_open_appointment(const Appointment& appt, const DateTime& date);
Nice catch!

2021-07-28 20:39 UTC, tari01 commented
> Found a few things that I think need fixing, from a quick look over.

Thanks for looking at this. I've corrected what I could.

2021-08-29 12:05 UTC, sunweaver approved these changes
LGTM. I have added some extra commits. Please take a look at them and ping me back. I will merge then.

2021-08-29 23:33 UTC, merged