tests/manual: Update and fix text
AyatanaIndicators/ayatana-indicator-datetime pull request #71
Opened 2021-11-02 16:29 UTC by tari01

@sunweaver 

I have modified this the best I could, but I wonder if we need this file at all - it seems to be an orphan...

2021-11-02 21:33 UTC, sunweaver requested changes
Please look at my suggestion for changes and nod / shake head...

2021-11-02 21:33 UTC, sunweaver commented on tests/manual
>  <dl>
mate-items-check?

2021-11-02 21:33 UTC, sunweaver commented on tests/manual
> +Test-case ayatana-indicator-datetime/MATE-and-other-desktops-greeter-items-check
arctica-greeter-items-check?

2021-11-02 21:33 UTC, sunweaver commented on tests/manual
> +        <dd>If the device supports haptic feedback, confirm the alarm vibrates.</dd>
possibly add a FIXME here? Haptics are currently commented out / not yet ported to hfd.

2021-11-03 01:06 UTC, tari01 commented
> Please look at my suggestions for changes and nod / shake head...

Nod. Makes sense.

2021-11-03 08:00 UTC, sunweaver approved these changes
LGTM

2021-11-03 08:16 UTC, merged