.build.yml: Build lomiri-url-dispatcher from source during CI builds.
AyatanaIndicators/ayatana-indicator-datetime pull request #75
Opened 2021-11-08 15:43 UTC by sunweaver

2021-11-08 17:57 UTC, tari01 requested changes

2021-11-08 17:57 UTC, tari01 commented on .build.yml
> +  -     git clone --depth 1  https://github.com/ubports/core/lomiri-url-dispatcher.git lomiri-url-dispatcher-build
https://gitlab.com/ubports/core/lomiri-url-dispatcher.git

2021-11-08 18:41 UTC, sunweaver commented on .build.yml
> +  -     git clone --depth 1  https://github.com/ubports/core/lomiri-url-dispatcher.git lomiri-url-dispatcher-build
Amended.

2021-11-08 23:22 UTC, tari01 requested changes

2021-11-08 23:22 UTC, tari01 commented on .build.yml
> +  -     git clone --depth 1  https://github.com/ubports/core/lomiri-url-dispatcher.git lomiri-url-dispatcher-build
It's github again :-)

2021-11-09 11:13 UTC, sunweaver commented
@tari01: should now be ok... Sorry for the hassle.

2021-11-09 23:47 UTC, tari01 requested changes
Building `lomiri-url-dispatcher` requires `liblomiri-app-launch-dev`. It needs to be added as a temporary dependency.

UPDATE: I've just tried adding **lomiri-app-launch**, but that one again has dependecies, so we are in dependency-hell with this. Maybe we should disable this for Ubuntu and have it only for Debian, pulling from Debian repositories?

2021-11-17 12:56 UTC, sunweaver commented
@tari01 I have decided to cancel this PR #75. The dependency pile behind lomiri-url-dispatcher is far to big (lomiri-app-launch, lomiri-api, mir, wlcs). Nothing we should do during CI builds if the distro doesn't provided that stack of dependencies.

2021-11-17 12:56 UTC, closed without merging