Re-enable haptic using hfd-service
AyatanaIndicators/ayatana-indicator-datetime pull request #78
Opened 2021-11-17 09:19 UTC by tari01

fixes https://github.com/AyatanaIndicators/ayatana-indicator-datetime/issues/67

2021-11-17 12:37 UTC, sunweaver commented
@mariogrip can you take a look at the usensord -> hfd port in ayatana-indicator-datetime? Thanks.

2021-11-17 12:38 UTC, sunweaver approved these changes
Looks good for me. But @mariogrip should give his 5¢ on this.

2021-11-18 12:30 UTC, mariogrip requested changes
Small nitpick, otherwise it looks good

2021-11-18 12:30 UTC, mariogrip commented on src/haptic.cpp
>              case MODE_PULSE: // the only mode currently supported... :)
I guess we dont need this switch anymore, since we dont do anything in here.

2021-11-18 12:58 UTC, tari01 commented on src/haptic.cpp
>              case MODE_PULSE: // the only mode currently supported... :)
I sooooo wanted to drop this, now I finally can.

2021-11-18 13:37 UTC, mariogrip approved these changes
LGTM :+1:

2021-11-18 13:43 UTC, merged