Remove cppcheck suppressions and fix errors/warnings
AyatanaIndicators/ayatana-indicator-datetime pull request #86
Opened 2021-12-16 12:09 UTC by tari01

2021-12-17 08:58 UTC, sunweaver requested changes
@tari01: You remove a lot of code in this PR without properly documenting the underlying reasonings. Please split out those removals into extra commits, maybe even an extra PR and document more thoroughly the why. Thanks.

2021-12-17 08:58 UTC, sunweaver commented on src/menu.cpp
> -                return a_after_today;
These changes feel like you lost some code in this commit. Please have this code removal as a separate commit / PR and explain better why you think removing this is good.

2021-12-17 08:58 UTC, sunweaver commented on tests/print-to.h
> -{
Simply sneaking in a test-removal into this commit is not appropriate. Separate commit, please with good explanation on why you do this.

2021-12-17 08:58 UTC, sunweaver commented on tests/test-menu-appointments.cpp
> -
also a massive code removal without proper explanations... Please amend.

2021-12-17 11:50 UTC, tari01 commented on tests/print-to.h
> -{
Unused file - added separate commit.

2021-12-17 11:51 UTC, tari01 commented on tests/test-menu-appointments.cpp
> -
Unused variables - added separate commit.

2021-12-17 12:05 UTC, tari01 commented on src/menu.cpp
> -                return a_after_today;
Comparing variables with same value - removed block in separate commit.

2021-12-17 15:37 UTC, sunweaver reviewed
Please revisit the a_after_today / b_after_today code block removal. I proposed an alternative solution / fix in the inline discusssion.

2021-12-17 15:37 UTC, sunweaver commented on src/menu.cpp
> -                return a_after_today;
@tari01 maybe it should read

```
            const bool a_after_today = (a.begin > end_of_day) || (a.end > end_of_day);
            const bool b_after_today = (b.begin > end_of_day) || (b.end > end_of_day);
            if (a_after_today != b_after_today)
                return a_after_today;
```

????

2021-12-20 11:36 UTC, tari01 commented on src/menu.cpp
> -                return a_after_today;
> @tari01 maybe it should read
> 
> ```
>             const bool a_after_today = (a.begin > end_of_day) || (a.end > end_of_day);
>             const bool b_after_today = (b.begin > end_of_day) || (b.end > end_of_day);
>             if (a_after_today != b_after_today)
>                 return a_after_today;
> ```
> 
> ????

I've tried all sorts of permutations of a and b, but it breaks the appointment ordering. I have a feeling this is a leftover from a previous approach that was replaced by adding more code blocks to this section. As things are now, the appointments are properly ordered - both in unit tests and the live installation.

2022-01-27 14:08 UTC, sunweaver commented
@tari01 Hi! Any new status on this?

2022-01-27 19:20 UTC, tari01 commented
> @tari01 Hi! Any new status on this?

Yes, I commented:

https://github.com/AyatanaIndicators/ayatana-indicator-datetime/pull/86#discussion_r772293867

2022-02-08 21:04 UTC, sunweaver approved these changes
Ok, then. Let's merge this.

2022-02-08 21:05 UTC, merged